import type { VenueMap } from "./types"

// Generate mock venue data
export const createMockVenue = (): VenueMap => ({
  id: "venue-1",
  name: "Grand Arena",
  dimensions: { width: 1200, height: 800 },
  stage: {
    position: { x: 400, y: 50 },
    dimensions: { width: 400, height: 80 },
    label: "Main Stage",
  },
  elements: [
    // Front rows (VIP)
    {
      id: "row-a",
      type: "seat-row",
      position: { x: 200, y: 180 },
      seats: 20,
      rowLabel: "A",
      curved: true,
      curveAngle: 10,
      spacing: 32,
      tier: "vip",
    },
    {
      id: "row-b",
      type: "seat-row",
      position: { x: 180, y: 220 },
      seats: 22,
      rowLabel: "B",
      curved: true,
      curveAngle: 8,
      spacing: 32,
      tier: "vip",
    },
    // Middle rows (Premium)
    {
      id: "row-c",
      type: "seat-row",
      position: { x: 160, y: 280 },
      seats: 24,
      rowLabel: "C",
      curved: false,
      curveAngle: 0,
      spacing: 32,
      tier: "premium",
    },
    {
      id: "row-d",
      type: "seat-row",
      position: { x: 160, y: 320 },
      seats: 24,
      rowLabel: "D",
      curved: false,
      curveAngle: 0,
      spacing: 32,
      tier: "premium",
    },
    {
      id: "row-e",
      type: "seat-row",
      position: { x: 160, y: 360 },
      seats: 24,
      rowLabel: "E",
      curved: false,
      curveAngle: 0,
      spacing: 32,
      tier: "premium",
    },
    // Back rows (Standard)
    {
      id: "row-f",
      type: "seat-row",
      position: { x: 140, y: 420 },
      seats: 26,
      rowLabel: "F",
      curved: false,
      curveAngle: 0,
      spacing: 32,
      tier: "standard",
    },
    {
      id: "row-g",
      type: "seat-row",
      position: { x: 140, y: 460 },
      seats: 26,
      rowLabel: "G",
      curved: false,
      curveAngle: 0,
      spacing: 32,
      tier: "standard",
    },
    {
      id: "row-h",
      type: "seat-row",
      position: { x: 140, y: 500 },
      seats: 26,
      rowLabel: "H",
      curved: false,
      curveAngle: 0,
      spacing: 32,
      tier: "standard",
    },
    // VIP Boxes
    {
      id: "box-1",
      type: "box",
      position: { x: 50, y: 180 },
      dimensions: { width: 100, height: 120 },
      capacity: 8,
      label: "Box 1",
      amenities: ["Private Bar", "Catering", "VIP Entrance"],
      tier: "vip",
    },
    {
      id: "box-2",
      type: "box",
      position: { x: 1050, y: 180 },
      dimensions: { width: 100, height: 120 },
      capacity: 8,
      label: "Box 2",
      amenities: ["Private Bar", "Catering", "VIP Entrance"],
      tier: "vip",
    },
    // Standing Areas
    {
      id: "standing-1",
      type: "standing",
      position: { x: 300, y: 580 },
      dimensions: { width: 600, height: 100 },
      capacity: 200,
      label: "General Standing",
      tier: "economy",
    },
    // Tables
    {
      id: "table-1",
      type: "table",
      position: { x: 100, y: 580 },
      seats: 6,
      shape: "round",
      label: "T1",
      tier: "premium",
    },
    {
      id: "table-2",
      type: "table",
      position: { x: 1000, y: 580 },
      seats: 6,
      shape: "round",
      label: "T2",
      tier: "premium",
    },
  ],
})

export const generateId = () => `el-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
